config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get 'home/index'
resources :products do
	resources :comments
end
resources :categories

root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
has_many :products
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :images, AvatarUploader
acts_as_commentable
belongs_to :user
belongs_to :category

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController


def show
    @category = Category.find(params[:id])
  end
 
def new
  end
def create
  @category = Category.new(category_params)
 
  @category.save
  redirect_to @category
end
private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    #byebug
    @article = Product.find(params[:product_id])
   @comment = @article.comments.new(comment_params)
    @comment.user_id=current_user.id
    @comment.save
     redirect_to product_path(@article)
end
private
    def comment_params
      params.require(:comment).permit(:title, :comment)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create, :update, :destroy]

def index

  if current_user
     @products= Product.where(user_id: current_user.id)
  
else
  @products=Product.all
end 
end

def show
      @comment = Comment.new
	    @product = Product.find(params[:id])
end
def new
	 @product = Product.new
	end

	
def create
  @product = Product.new(product_params)
 if @product.save
  redirect_to @product

  else
    render 'new'
end
end
private
  def product_params
    params.require(:product).permit(:name, :description, :location, :category_id, :images, :user_id)
  end

	end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/new.html.erb
<%= form_for :category, url: categories_path do |f| %>
  <p>
    <%= f.label :category_id %><br>
    <%= f.text_field :category_id%>
  </p>
 <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p>
  <strong>Category_id:</strong>
  <%= @category.id %>
</p

app/views/home/index.html.erb
<h1>SecondApp</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecondApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
<div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
</div>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>Listing products</h1>
 <%= link_to 'New product', new_product_path %>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Location</th>
    <th>Category_id</th>
    <th>Images</th>
    <th>Location</th>
    <th>User_id</th>


  </tr>
 
  <% @products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.description %></td>
      <td><%= product.location %></td>
      <td><%= product.category_id %></td>
      <td><%= product.images %></td>
      <td><%= product.user_id %></td>


      <td><%= link_to 'Show', product_path(product) %></td>
            <td><%= link_to 'Edit', edit_product_path(product) %></td>
            <td><%= link_to 'Destroy', product_path(product),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>

    </tr>
  <% end %>
</table>
<%= link_to 'Back', home_index_path %>

app/views/products/new.html.erb
<%= form_for :product, url: products_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 <p>
    <%= f.label :location %><br>
    <%= f.text_area :location %>
  </p>

  <p>
  <%= f.label :category_id %><br />
  <%= f.collection_select :category_id, Category.all, :id,:name %>
</p>
    <p>
    <%= f.label :images %><br>
    <%= f.file_field :images %>
  </p>

  <p>
  <%= f.label :user_id %><br />
  <%= f.collection_select :user_id, User.all, :id, :email %>
</p>

    

  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>
 
<p>
  <strong>Location:</strong>
  <%= @product.location %>
</p>

<p>
  <strong>Category_id:</strong>
  <%= @product.category.name %>
</p>

<p>
  <strong>Images:</strong>
  <%=image_tag  @product.images %>
</p>

<p>
  <strong>User_id:</strong>
  <%= @product.user.email %>
</p>


<h2>Comments</h2>
<% @product.comments.each do |comment| %>
<p>
  <strong>Commenter:</strong>
  <%= comment.title %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.comment %>
</p>
<p>
<%= comment.user.email %>
</p>
<% end %>
 
<h2>Add a comment:</h2>
 <%# form_for @comment, url: "/rakesh" do |f| %>
  <%= form_for([@product, @product.comments.build]) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>